PackageIdentifier: Kaspersky.SecurityCloud
Publisher: Kaspersky
PackageName: Kaspersky Security Cloud
PackageVersion: 4.21.0.0
License: Kaspersky EULA
InstallerType: exe
LicenseUrl: https://www.kaspersky.com/end-user-license-agreement
Moniker: SecurityCloud
Tags:
- Kaspersky
ShortDescription: Kaspersky Security Cloud
PackageUrl: https://www.kaspersky.com/
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://raw.githubusercontent.com/RavenMacDaddy/winget-apps/main/files/ks4.021.3.10.391en_25092.exe
  InstallerSha256: F94439C32C298493449B90A45B3A72F77CD2FB198034ABFC849E1753397D84CB
  InstallerLocale: En
  InstallerSwitches:
    Silent: /quiet /norestart
    SilentWithProgress: /passive /norestart
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0