PackageIdentifier: Kaspersky.SecurityCloud
Publisher: Kaspersky
PackageName: Kaspersky Security Cloud
PackageVersion: 4.021.3.10.391
License: Kaspersky EULA
InstallerType: exe
LicenseUrl: https://www.kaspersky.com/end-user-license-agreement
Moniker: SecurityCloud
Tags:
- Kaspersky
ShortDescription: Kaspersky Security Cloud
PackageUrl: https://www.kaspersky.com/
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://raw.githubusercontent.com/RavenMacDaddy/winget-apps/main/files/Kaspersky%20Security%20Cloud%20Swe-EU/ks4.021.3.10.391sv_24986.exe
  InstallerSha256: B5E0E6D2E5BBA57E634B6BD6E2B3ABC909A53A91DB8260B7241F918A90B9130D
  InstallerLocale: Swe
  InstallerSwitches:
    Silent: /s /mybirthdate=1980-01-01 /pSKIPPRODUCTCHECK=1 /pALLOWREBOOT=0
PackageLocale: sv-SE
ManifestType: singleton
ManifestVersion: 1.0.0