# Automatically updated by the winget bot at 2021/Mar/31
PackageIdentifier: TIDAL.TIDAL
Publisher: TIDAL Music AS
PackageName: TIDAL
PackageVersion: 2.26.1
Moniker: TIDAL
MinimumOSVersion: 10.0.0.0
ShortDescription: TIDAL is a global music streaming service with high fidelity sound, hi-def video quality, and expertly curated playlists.
PackageUrl: https://tidal.com
License: Copyright (c) 2020 Aspiro AB
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://download.tidal.com/desktop/TIDALSetup.exe
  InstallerSha256: 113B52B4FEE03C344FA9AC5E2DBCC3B91C6EF6A1EF97A0C934AEE9EBB9736E85
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
